### ISSUE TITLE
Language Selection

### ISSUE THREAD

**Issue by RussW** [micker/mod_joomadmin#1]
Language selection should default to "All" unless otherwise selected or sites not utilising multi-lingual features will not show preselected items/categories etc

**Comment by micker** [comment]
hello and thanks for testing ... 
corrected here https://github.com/micker/mod_joomadmin/commit/f5843d982a7fa60e0724e2004074619dfdfd0839

**Comment by RussW** [comment]
thanks, will continue to test, thank you for taking the time, I manually produce an "admin" section for our sites and this is a good start.

**Comment by RussW** [comment]
Tested : Fixed
