### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ghost** [micker/mod_joomadmin#19]
that dashboard really work in joomla 4 ty

**Comment by micker** [comment]
Hello master branch only works on j3 use v2 branch for j4 please

**Comment by ghost** [comment]
I found 2.6 and it works on joomla 4, but only default and icon view, and
I'm not programmer so that stuff on github are complicate  for me, u should
put normal download button somewhere

Jasna


sub, 5. ožu 2022. u 13:52 Berges Yannick ***@***.***> napisao
je:

**Comment by micker** [comment]
Hello i dont understand on right part you have release buttons. Can you explain more about view ?

**Comment by ghost** [comment]
[image: image.png]

<https://funart.hr>


sub, 5. ožu 2022. u 15:12 Berges Yannick ***@***.***> napisao
je:

**Comment by ghost** [comment]
Ok, this is what I think:
I would like to have some custom buttons everywhere, not just inseparate
tab, for eg here - I want make button for make new page (with page
builder), that is better to be here than on custom tab mixed with some
other buttons like "backup"
[image: image.png]




sub, 5. ožu 2022. u 15:16 Jasna Sontag ***@***.***> napisao je:

**Comment by ghost** [comment]
I  can't choose icon
[image: image.png]
it doesn't work

sub, 5. ožu 2022. u 15:46 Jasna Sontag ***@***.***> napisao je:

**Comment by ghost** [comment]
o I can but after saving:
[image: image.png]


sub, 5. ožu 2022. u 15:49 Jasna Sontag ***@***.***> napisao je:

**Comment by micker** [comment]
Your image seems broken i didnt see anything

**Comment by ghost** [comment]
omg, I answered by gmail, not here
never mind
dashboard works, but I don't like it a lot
I like more Custom Quick Icons

**Comment by ghost** [comment]
ok I discovered it more and it is not so bad - I disabled all tabs except
free and made free tabs with icons I want, now it is good :-D


sub, 5. ožu 2022. u 15:59 Berges Yannick ***@***.***> napisao
je:

**Comment by micker** [comment]
Cool happy to share it
