### ISSUE TITLE
Joomla 3 issue

### ISSUE THREAD

**Issue by webiedesign** [micker/mod_joomadmin#20]
I mostly work on new Joomla 4 sites now and the newest release works great. I am wanting to add this on a Joomla 3 site now and get an error of: Class 'Joomla\Module\Quickicon\Administrator\Event\QuickIconsEvent' not found
when I publish the module. Any ideas on how I can fix this would be great

**Comment by micker** [comment]
hello for j3 use 1.X version
https://github.com/micker/mod_dashboard/releases/tag/1.7
