### ISSUE TITLE
Error with Joomla 4.2.8

### ISSUE THREAD

**Issue by Martan404** [micker/mod_joomadmin#21]
After publishing the plugin to cpanel I get this error on my dashboard. 

`Argument 1 passed to Joomla\Plugin\Quickicon\Joomlaupdate\Extension\Joomlaupdate::getCoreUpdateNotification() must be an instance of Joomla\Module\Quickicon\Administrator\Event\QuickIconsEvent, instance of Joomla\Event\Event given, called in /var/www/joomla/libraries/vendor/joomla/event/src/Dispatcher.php on line 486 `

Using Joomla 4.2.8, PHP 7.4.33 and [Admin dashboard for Joomla4 v2.8](https://github.com/micker/mod_dashboard/releases/tag/v2.8)

**Comment by maxgdias** [comment]
Same for me.
Joomla 4.2.8 - PHP 8.1.14

**Comment by micker** [comment]
hello i will check it asap

**Comment by micker** [comment]
i think you have an old module version
please update to https://github.com/micker/mod_dashboard/releases/tag/v2.9
