### ISSUE TITLE
Fatal error caused when mod is published

### ISSUE THREAD

**Issue by zstergios** [micker/mod_joomadmin#22]
An error has occurred.

    0 Joomla\Plugin\Quickicon\OverrideCheck\Extension\OverrideCheck::onGetIcons(): Argument #1 ($event) must be of type Joomla\Module\Quickicon\Administrator\Event\QuickIconsEvent, Joomla\Event\Event given, called in C:\lxxxxx\libraries\vendor\joomla\event\src\Dispatcher.php on line 486 

Joomla 4.3.0

**Comment by micker** [comment]
hello please udpdate your module for 2.9 version
