### ISSUE TITLE
Feature Request : More Than One "Free Tab"

### ISSUE THREAD

**Issue by RussW** [micker/mod_joomadmin#5]
Having more than one "Free" tab would be useful, we tend to separate functions in to different tabs in our custom/html (hand coded) module

**Comment by micker** [comment]
yes its a good idea ... maybe i can study a repetable in a repaetable subform ...

**Comment by micker** [comment]
added via https://github.com/micker/mod_joomadmin/commit/adf4f9569629555c3d11f087589847363cb5b491
Can you test it ?
